# Generated by Django 5.2.1 on 2025-08-09 08:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TrackerApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='task',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9000000),
        ),
        migrations.AddField(
            model_name='task',
            name='type',
            field=models.CharField(choices=[('Not selected', 'Не выбрано'), ('Programming', 'Программирование'), ('Design', 'Дизайн'), ('Testing', 'Тестирование'), ('Marketing', 'Маркетинг / Реклама'), ('Arbitrage', 'Арбитраж(Трафика)'), ('Editing', 'Монтаж / Видеомонтаж')], default='Not selected', max_length=50),
        ),
        migrations.AlterField(
            model_name='comment',
            name='media',
            field=models.FileField(blank=True, null=True, upload_to='comments'),
        ),
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('Not selected', 'Не выбрано'), ('low', 'Низкий'), ('medium', 'Средний'), ('high', 'Высокий')], default='Не выбрано', max_length=60),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('Not selected', 'Не выбрано'), ('В ожидании', 'В ожидании'), ('В прогрессе', 'В прогрессе'), ('Готово', 'Готово')], default='Не выбрано', max_length=50),
        ),
    ]
